version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.GH_DB_TOKEN}}
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "40 * * * *"
    open-pull-requests-limit: 50
    registries:
      - github
    ignore:
      - dependency-name: "*-grading-tests"
